{{- if .Values.volumeGroupSnapshotClass.create -}}
apiVersion: groupsnapshot.storage.k8s.io/v1beta1
kind: VolumeGroupSnapshotClass
metadata:
  name: {{ .Values.volumeGroupSnapshotClass.name }}
deletionPolicy: Delete
driver: hostpath.csi.k8s.io
{{- end -}}
