apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-pvc-restore
spec:
  storageClassName: csi-hostpath-sc
  volumeMode: Block
  dataSource:
    name: raw-pvc-snapshot # defined in the csi-block-pvc-snapshot.yaml
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
