apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-raw-clone
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: pvc-raw  # definded in the csi-pvc-block.yaml
    kind: PersistentVolumeClaim
    apiGroup: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
